//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.khita.cn.samples", ConfigurationName="ServiceReference1.IWinStation")]
    public interface IWinStation {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.khita.cn.samples/IWinStation/UnLockWinStation", ReplyAction="http://www.khita.cn.samples/IWinStation/UnLockWinStationResponse")]
        void UnLockWinStation(string username, string password, string other, int type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.khita.cn.samples/IWinStation/UnLockWinStation", ReplyAction="http://www.khita.cn.samples/IWinStation/UnLockWinStationResponse")]
        System.Threading.Tasks.Task UnLockWinStationAsync(string username, string password, string other, int type);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWinStationChannel : ConsoleAppClient.ServiceReference1.IWinStation, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WinStationClient : System.ServiceModel.ClientBase<ConsoleAppClient.ServiceReference1.IWinStation>, ConsoleAppClient.ServiceReference1.IWinStation {
        
        public WinStationClient() {
        }
        
        public WinStationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WinStationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WinStationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WinStationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void UnLockWinStation(string username, string password, string other, int type) {
            base.Channel.UnLockWinStation(username, password, other, type);
        }
        
        public System.Threading.Tasks.Task UnLockWinStationAsync(string username, string password, string other, int type) {
            return base.Channel.UnLockWinStationAsync(username, password, other, type);
        }
    }
}
